name: Deploy (cloud-chat)

on:
  push:
    branches: main
    paths:
      - ".github/workflows/deploy-chat.yml"
      - "examples/cloud-chat/**"
      - "!**.md"

jobs:
  deploy:
    runs-on: [ubuntu-20.04]
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
    defaults:
      run:
        working-directory: examples/cloud-chat
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: v16
      - run: npm ci
      - run: npm test
      - run: npm ci
        working-directory: examples/cloud-chat/frontend
      - run: npm run build
        working-directory: examples/cloud-chat/frontend
      - run: npm run deploy
