name: Pull request (cloud-chat)

on:
  pull_request:
    types: [closed]
    paths:
      - ".github/workflows/pr-chat.yml"
      - "examples/cloud-chat/**"
      - "!**.md"

jobs:
  test:
    name: Delete preview instance
    runs-on: [ubuntu-20.04]
    env:
      SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
      PREVIEW_INSTANCE_NAME: pr-${{ github.event.number }}
    defaults:
      run:
        working-directory: examples/cloud-chat
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: v16
      - run: npm ci
      - run: npm run preview:delete
